spring:
  application:
    name: zuul
server:
  port: 9000
zuul:
  routes:
    api-a:
      path: /indent/**
      serviceId: indent-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/